spring:
  profiles.active: 

---

spring: 
  profiles: default
  application:
   name: Badgerr
server:
  port: 8081
  
badges: 
  github: 
    issues: "[![GitHub issues](https://img.shields.io/github/issues/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/issues)" 
    forks: "[![GitHub forks](https://img.shields.io/github/forks/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/network)"
    stars:  "[![GitHub stars](https://img.shields.io/github/stars/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/stargazers)"
    license:  "[![GitHub license](https://img.shields.io/github/license/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/blob/master/LICENSE)"
    clone: "git clone git@github.com:USERNAME/REPONAME.git"
  sonar:
    measure: "[![Sonarcloud Status](https://sonarcloud.io/api/project_badges/measure?project=USERNAME_REPONAME&metric=alert_status)](https://sonarcloud.io/dashboard?id=USERNAME_REPONAME)"
  lgtm:
    alerts: "[![Total alerts](https://img.shields.io/lgtm/alerts/g/USERNAME/REPONAME.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/USERNAME/REPONAME/alerts/)"
    grade: "[![Language grade: Java](https://img.shields.io/lgtm/grade/java/g/USERNAME/REPONAME.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/USERNAME/REPONAME/context:java)"
  travis:
    status: "[![Build Status](https://travis-ci.org/USERNAME/REPONAME.svg?branch=master)](https://travis-ci.org/USERNAME/REPONAME)"
  config:
    placeholder: REPONAME
    githubreposapiurl: "https://api.github.com/users/USERNAME/repos?per_page=100"
---
spring: 
  profiles: default-redis
  application:
   name: Badgerr
server:
  port: 8081
  
badges: 
  github: 
    issues: "[![GitHub issues](https://img.shields.io/github/issues/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/issues)" 
    forks: "[![GitHub forks](https://img.shields.io/github/forks/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/network)"
    stars:  "[![GitHub stars](https://img.shields.io/github/stars/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/stargazers)"
    license:  "[![GitHub license](https://img.shields.io/github/license/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/blob/master/LICENSE)"
    clone: "git clone git@github.com:USERNAME/REPONAME.git"
  sonar:
    measure: "[![Sonarcloud Status](https://sonarcloud.io/api/project_badges/measure?project=USERNAME_REPONAME&metric=alert_status)](https://sonarcloud.io/dashboard?id=USERNAME_REPONAME)"
  lgtm:
    alerts: "[![Total alerts](https://img.shields.io/lgtm/alerts/g/USERNAME/REPONAME.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/USERNAME/REPONAME/alerts/)"
    grade: "[![Language grade: Java](https://img.shields.io/lgtm/grade/java/g/USERNAME/REPONAME.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/USERNAME/REPONAME/context:java)"
  travis:
    status: "[![Build Status](https://travis-ci.org/USERNAME/REPONAME.svg?branch=master)](https://travis-ci.org/USERNAME/REPONAME)"
  config:
    placeholder: REPONAME
    githubreposapiurl: "https://api.github.com/users/USERNAME/repos?per_page=100"
